package com.example.maskdetection

const val MESSAGE_STATE_CHANGE = 1
const val MESSAGE_WRITE = 2
const val MESSAGE_READ = 3
const val MESSAGE_TOAST = 4
const val MESSAGE_DEVICE_FOUND = 5
const val MESSAGE_UPDATE_WIFI_LIST = 6
const val MESSAGE_UPDATE_IMAGE_LIST = 6
const val MESSAGE_UPDATE_IMAGE_FRAGMENT = 7
const val MESSAGE_UPDATE_IMAGE_COMPLETE = 8

const val MESSAGE_BACKGROUND_ENABLE = 9
const val MESSAGE_BACKGROUND_DISABLE = 10